import { TrendingUp, Info, Sparkles } from "lucide-react";
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover";

const DIRECTION_STYLE = {
    Positive: { dot: "bg-emerald-500", text: "text-emerald-600 dark:text-emerald-400" },
    Negative: { dot: "bg-rose-500", text: "text-rose-600 dark:text-rose-400" },
    Mixed: { dot: "bg-amber-500", text: "text-amber-600 dark:text-amber-400" },
    Unclear: { dot: "bg-muted-foreground", text: "text-muted-foreground" },
};

/**
 * Section #9 in the result card. Purely presentational; when there are no
 * impact items the ENTIRE section (header, badge, disclaimer) is hidden —
 * never rendered with an empty-state placeholder.
 */
export function ImpactAnalysis({ data }) {
    const items = Array.isArray(data?.items) ? data.items : [];
    if (items.length === 0) return null;

    return (
        <div data-testid="impact-analysis" className="w-full">
            <div className="flex items-center justify-between flex-wrap gap-2">
                <div className="label-eyebrow flex items-center gap-2">
                    <TrendingUp className="h-3.5 w-3.5" strokeWidth={1.75} />
                    9 · Impact Analysis
                </div>
                <Popover>
                    <PopoverTrigger asChild>
                        <button
                            type="button"
                            className="text-muted-foreground hover:text-foreground transition-colors"
                            aria-label="AI attribution"
                            data-testid="impact-ai-attribution"
                        >
                            <Sparkles className="h-3.5 w-3.5" strokeWidth={1.75} />
                        </button>
                    </PopoverTrigger>
                    <PopoverContent className="w-64 text-xs" side="top">
                        Generated by Claude (Anthropic) based on this article's content.
                    </PopoverContent>
                </Popover>
            </div>

            <div className="mt-4 grid gap-4 md:grid-cols-2">
                {items.map((it, i) => {
                    const style = DIRECTION_STYLE[it.direction] || DIRECTION_STYLE.Unclear;
                    return (
                        <div key={i} className="cell" data-testid={`impact-item-${i}`}>
                            <div className="flex items-start justify-between gap-2 flex-wrap mb-3">
                                <div className="text-xs font-semibold tracking-wide text-foreground">
                                    {it.aspect}
                                </div>
                                <div className="flex items-center gap-2 shrink-0">
                                    <span className={`h-2 w-2 rounded-full ${style.dot}`} />
                                    <span className={`text-xs font-medium ${style.text}`}>
                                        {it.direction}
                                    </span>
                                    <span className="text-[10px] uppercase tracking-widest
                                        text-muted-foreground font-mono-alt border
                                        border-border rounded-full px-2 py-0.5">
                                        {it.certainty}
                                    </span>
                                </div>
                            </div>
                            <p className="text-sm leading-relaxed">{it.description}</p>
                        </div>
                    );
                })}
            </div>

            {data.disclaimer && (
                <p
                    className="mt-3 text-xs text-muted-foreground flex items-center gap-1"
                    data-testid="impact-disclaimer"
                >
                    <Info className="h-3 w-3" strokeWidth={1.75} />
                    {data.disclaimer}
                </p>
            )}
        </div>
    );
}
